language: nix

before_install:
  - |
    function should-deploy {
        [[ "${TRAVIS_PULL_REQUEST}" == "false" && \
           "${TRAVIS_BRANCH}" == "master" ]]
    }
  - |
    function decrypt-ssh-key {
        openssl aes-256-cbc \
            -K  $encrypted_a6e9969759b7_key \
            -iv $encrypted_a6e9969759b7_iv \
            -in tools/travis/ssh-key.enc \
            -out tools/travis/ssh-key -d
        chmod 600 tools/travis/ssh-key
    }

script:
  - nix-build
  - |
    nix-shell --run "set -e
        mkdir build && cd build
        cmake ..
        make check
    "

after_success:
  - |
    if should-deploy; then
        decrypt-ssh-key
        nix-shell --run "set -e
            cd build
            make docs
            make upload-docs
        "
    fi
