language: nix

matrix:
  include:
    - env: TYPE=Debug   COMPILER=clang_38
    - env: TYPE=Release COMPILER=clang_38
    - env: TYPE=Debug   COMPILER=gcc5
    - env: TYPE=Release COMPILER=gcc5

before_install:
  - |
    function should-deploy {
        [[ "${TRAVIS_PULL_REQUEST}" == "false" && \
           "${TRAVIS_BRANCH}" == "master" ]]
    }
  - |
    function decrypt-ssh-key {
        openssl aes-256-cbc \
            -K  $encrypted_a6e9969759b7_key \
            -iv $encrypted_a6e9969759b7_iv \
            -in tools/travis/ssh-key.enc \
            -out tools/travis/ssh-key -d
        chmod 600 tools/travis/ssh-key
    }
  - |
    function with-nix {
        nix-shell --argstr compiler $COMPILER --run "set -e; $1"
    }

install:
  - with-nix "echo prepared environment!"

script:
  - nix-build
  - |
    with-nix "
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=$TYPE
        make check
    "

after_success:
  - |
    if should-deploy; then
        decrypt-ssh-key
        with-nix "
            cd build
            make docs
            make upload-docs
        "
    fi
